// @ts-check

import eslint from '@eslint/js';
import tseslint from 'typescript-eslint';

const browserGlobals = {
  window: 'readonly',
  document: 'readonly',
  navigator: 'readonly',
  location: 'readonly',
  history: 'readonly',
  localStorage: 'readonly',
  sessionStorage: 'readonly',
  screen: 'readonly',
  devicePixelRatio: 'readonly',
  innerWidth: 'readonly',
  innerHeight: 'readonly',
  fetch: 'readonly',
  Headers: 'readonly',
  Request: 'readonly',
  Response: 'readonly',
  WebSocket: 'readonly',
  EventSource: 'readonly',
  Event: 'readonly',
  CustomEvent: 'readonly',
  KeyboardEvent: 'readonly',
  MouseEvent: 'readonly',
  PointerEvent: 'readonly',
  WheelEvent: 'readonly',
  DragEvent: 'readonly',
  FocusEvent: 'readonly',
  InputEvent: 'readonly',
  ClipboardEvent: 'readonly',
  PopStateEvent: 'readonly',
  HashChangeEvent: 'readonly',
  MessageEvent: 'readonly',
  ErrorEvent: 'readonly',
  XMLHttpRequest: 'readonly',
  FormData: 'readonly',
  URL: 'readonly',
  URLSearchParams: 'readonly',
  Blob: 'readonly',
  File: 'readonly',
  FileReader: 'readonly',
  Image: 'readonly',
  DOMParser: 'readonly',
  DOMException: 'readonly',
  AbortController: 'readonly',
  AbortSignal: 'readonly',
  IntersectionObserver: 'readonly',
  ResizeObserver: 'readonly',
  MutationObserver: 'readonly',
  PerformanceObserver: 'readonly',
  requestAnimationFrame: 'readonly',
  cancelAnimationFrame: 'readonly',
  requestIdleCallback: 'readonly',
  cancelIdleCallback: 'readonly',
  getComputedStyle: 'readonly',
  matchMedia: 'readonly',
  getSelection: 'readonly',
  scrollTo: 'readonly',
  scrollBy: 'readonly',
  scrollX: 'readonly',
  scrollY: 'readonly',
  open: 'readonly',
  print: 'readonly',
  alert: 'readonly',
  confirm: 'readonly',
  prompt: 'readonly',
  setTimeout: 'readonly',
  clearTimeout: 'readonly',
  setInterval: 'readonly',
  clearInterval: 'readonly',
  queueMicrotask: 'readonly',
  structuredClone: 'readonly',
  atob: 'readonly',
  btoa: 'readonly',
  crypto: 'readonly',
  performance: 'readonly',
  console: 'readonly',
  self: 'readonly',
  top: 'readonly',
  parent: 'readonly',
  Element: 'readonly',
  HTMLElement: 'readonly',
  HTMLInputElement: 'readonly',
  HTMLTextAreaElement: 'readonly',
  HTMLSelectElement: 'readonly',
  HTMLButtonElement: 'readonly',
  HTMLFormElement: 'readonly',
  HTMLAnchorElement: 'readonly',
  HTMLTemplateElement: 'readonly',
  HTMLIFrameElement: 'readonly',
  HTMLCanvasElement: 'readonly',
  CanvasRenderingContext2D: 'readonly',
  Node: 'readonly',
  NodeList: 'readonly',
  ShadowRoot: 'readonly',
  DocumentFragment: 'readonly',
  EventTarget: 'readonly',
  MediaQueryList: 'readonly',
  Worker: 'readonly',
  BroadcastChannel: 'readonly',
  Notification: 'readonly',
  TextEncoder: 'readonly',
  TextDecoder: 'readonly',
  CSS: 'readonly',
  ResizeObserverEntry: 'readonly',
  // Globals defined by other classic scripts on the page.
  alIcon: 'readonly',
  showToast: 'readonly',
  monaco: 'readonly',
};

const nodeGlobals = {
  Buffer: 'readonly',
  fetch: 'readonly',
  URL: 'readonly',
  URLSearchParams: 'readonly',
  TextEncoder: 'readonly',
  TextDecoder: 'readonly',
  structuredClone: 'readonly',
  queueMicrotask: 'readonly',
  setImmediate: 'readonly',
  setInterval: 'readonly',
  clearInterval: 'readonly',
  setTimeout: 'readonly',
  clearTimeout: 'readonly',
  __dirname: 'readonly',
  __filename: 'readonly',
};

export default tseslint.config(
  {
    ignores: [
      'dist/**',
      'storage/**',
      'coverage/**',
      'public/.vite/**',
      'public/uploads/**',
      'node_modules/**',
    ],
  },
  eslint.configs.recommended,
  tseslint.configs.recommended,
  tseslint.configs.strict,
  tseslint.configs.stylistic,
  {
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'warn',
        { argsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-require-imports': 'off',
      '@typescript-eslint/no-non-null-assertion': 'warn',
      '@typescript-eslint/no-empty-function': 'warn',
      'no-console': 'warn',
      'no-debugger': 'error',
      eqeqeq: ['error', 'always'],
      curly: ['error', 'all'],
      semi: ['error', 'always'],
      quotes: ['warn', 'single'],
      indent: ['warn', 2],
      'prefer-const': 'error',
      'no-var': 'error',
      'object-shorthand': 'error',
      'prefer-template': 'warn',
      'no-throw-literal': 'error',
      'no-return-await': 'warn',
      'no-empty': 'warn',
      '@typescript-eslint/consistent-type-imports': 'warn',
      '@typescript-eslint/consistent-type-definitions': ['error', 'interface'],
      '@typescript-eslint/no-dynamic-delete': 'error',
      '@typescript-eslint/no-extraneous-class': [
        'error',
        { allowConstructorOnly: true },
      ],
    },
    languageOptions: {
      globals: {
        node: true,
        jest: true,
        module: true,
        process: true,
        setTimeout: true,
        clearTimeout: true,
        global: true,
        __dirname: true,
        require: true,
        exports: true,
        describe: true,
        it: true,
        expect: true,
        test: true,
        console: true,
        beforeEach: true,
        afterEach: true,
        beforeAll: true,
        afterAll: true,
      },
    },
  },
  {
    // Browser code: no type checker, so keep no-undef but give it the
    // real browser globals it needs.
    files: ['public/**/*.{js,mjs,cjs}', 'views/**/*.js'],
    languageOptions: {
      globals: browserGlobals,
    },
  },
  {
    // Node tooling scripts run under plain Node (ESM), not the server tsconfig.
    files: ['scripts/**/*.{js,mjs,ts,cts}', '*.mjs', '*.config.{js,mjs,ts}'],
    languageOptions: {
      globals: nodeGlobals,
    },
  },
  {
    // Vitest globals used by test files.
    files: ['tests/**/*.ts', 'tests/**/*.js', '**/*.test.ts'],
    languageOptions: {
      globals: {
        vi: 'readonly',
        suite: 'readonly',
        onTestFinished: 'readonly',
        inject: 'readonly',
      },
    },
  },
);
