import pg from 'pg';
import crypto from 'crypto';
import type {
  DatabaseHost,
  ServerDatabase,
} from '../../../generated/prisma/client';
import { decrypt, isEncrypted } from '../../../utils/encryption';

const IDENTIFIER_RE = /^[A-Za-z_][A-Za-z0-9_]*$/;
const GENERATED_PASSWORD_RE = /^[0-9a-f]{24}$/;
const DB_NAME_SLICE_LEN = 16;
const DB_USER_SLICE_LEN = 12;
const DB_PASS_RANDOM_BYTES = 12;

export interface DatabaseCredentials {
  databaseName: string;
  databaseUser: string;
  databasePassword: string;
}

function assertSafeIdentifier(value: string, label: string): void {
  if (!IDENTIFIER_RE.test(value) || value.length > 63) {
    throw new Error(
      `${label} "${value}" is not a valid PostgreSQL identifier.`,
    );
  }
}

function assertSafePassword(value: string): void {
  if (!GENERATED_PASSWORD_RE.test(value)) {
    throw new Error('Database password must be generated by the panel.');
  }
}

async function connect(host: DatabaseHost): Promise<pg.PoolClient> {
  // Decrypt password if it was encrypted by the panel, otherwise use as-is (plaintext legacy)
  const password = isEncrypted(host.password)
    ? decrypt(host.password, process.env.SESSION_SECRET || '')
    : host.password;

  const pool = new pg.Pool({
    host: host.host,
    port: host.port,
    user: host.username,
    password,
    database: 'postgres',
    connectionTimeoutMillis: 10_000,
    max: 1,
  });
  try {
    const client = await pool.connect();
    // Wrap pool.end so the client releases back and pool drains
    const originalEnd = client.release.bind(client);
    client.release = () => {
      originalEnd();
      pool.end();
    };
    return client;
  } catch (error) {
    await pool.end();
    const code = (error as { code?: string })?.code;
    if (code === 'ECONNREFUSED') {
      throw new Error(
        `PostgreSQL missing or not running on ${host.host}:${host.port} (connection refused)`,
        { cause: error },
      );
    }
    if (code === 'ENOTFOUND') {
      throw new Error(`PostgreSQL host not found: ${host.host}`, {
        cause: error,
      });
    }
    throw error instanceof Error
      ? error
      : new Error('Failed to connect to the database host');
  }
}

export async function provisionDatabase(
  host: DatabaseHost,
  serverId: string,
): Promise<DatabaseCredentials> {
  const hex = serverId.replace(/-/g, '');
  const dbName = `airlink_${hex.slice(0, DB_NAME_SLICE_LEN)}`;
  const dbUser = `al_${hex.slice(0, DB_USER_SLICE_LEN)}`;
  const dbPass = crypto.randomBytes(DB_PASS_RANDOM_BYTES).toString('hex');

  assertSafeIdentifier(dbName, 'Database name');
  assertSafeIdentifier(dbUser, 'Database user');
  assertSafePassword(dbPass);

  const conn = await connect(host);
  try {
    // Check if database exists
    const dbCheck = await conn.query(
      'SELECT 1 FROM pg_database WHERE datname = $1',
      [dbName],
    );
    if (dbCheck.rows.length === 0) {
      // PostgreSQL doesn't allow parameters in DDL identifiers — validated above
      await conn.query(`CREATE DATABASE "${dbName}"`);
    }

    // Create role if not exists
    const roleCheck = await conn.query(
      'SELECT 1 FROM pg_roles WHERE rolname = $1',
      [dbUser],
    );
    if (roleCheck.rows.length === 0) {
      await conn.query(`CREATE ROLE "${dbUser}" WITH LOGIN PASSWORD $1`, [
        dbPass,
      ]);
    } else {
      await conn.query(`ALTER ROLE "${dbUser}" WITH PASSWORD $1`, [dbPass]);
    }

    // Grant privileges
    await conn.query(
      `GRANT ALL PRIVILEGES ON DATABASE "${dbName}" TO "${dbUser}"`,
    );
    await conn.query(`GRANT ALL ON SCHEMA public TO "${dbUser}"`);
    // Grant default privileges for future objects
    await conn.query(
      `ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO "${dbUser}"`,
    );
    await conn.query(
      `ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO "${dbUser}"`,
    );
  } finally {
    conn.release();
  }

  return {
    databaseName: dbName,
    databaseUser: dbUser,
    databasePassword: dbPass,
  };
}

export async function deprovisionDatabase(
  host: DatabaseHost,
  db: ServerDatabase,
): Promise<void> {
  assertSafeIdentifier(db.databaseName, 'Database name');
  assertSafeIdentifier(db.databaseUser, 'Database user');

  const conn = await connect(host);
  try {
    // Terminate existing connections to the database
    await conn.query(
      'SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = $1',
      [db.databaseName],
    );
    await conn.query(`DROP DATABASE IF EXISTS "${db.databaseName}"`);
    await conn.query(`DROP ROLE IF EXISTS "${db.databaseUser}"`);
  } finally {
    conn.release();
  }
}

export async function rotateDatabasePassword(
  host: DatabaseHost,
  db: ServerDatabase,
): Promise<string> {
  assertSafeIdentifier(db.databaseUser, 'Database user');

  const newPassword = crypto.randomBytes(DB_PASS_RANDOM_BYTES).toString('hex');
  assertSafePassword(newPassword);
  const conn = await connect(host);
  try {
    await conn.query(`ALTER ROLE "${db.databaseUser}" WITH PASSWORD $1`, [
      newPassword,
    ]);
  } finally {
    conn.release();
  }
  return newPassword;
}

export async function testDatabaseHost(
  host: DatabaseHost,
): Promise<{ success: boolean; latency?: number; error?: string }> {
  const start = Date.now();
  try {
    const password = isEncrypted(host.password)
      ? decrypt(host.password, process.env.SESSION_SECRET || '')
      : host.password;

    const pool = new pg.Pool({
      host: host.host,
      port: host.port,
      user: host.username,
      password,
      database: 'postgres',
      connectionTimeoutMillis: 10_000,
      max: 1,
    });
    const client = await pool.connect();
    await client.query('SELECT 1');
    client.release();
    await pool.end();
    return { success: true, latency: Date.now() - start };
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Connection failed',
    };
  }
}
